### ISSUE TITLE
not working on Umbraco 8, but have a fix

### ISSUE THREAD

**Issue by lilyanapet** [skttl/Umbraco.SvgIconPicker#12]
The package was causing issues on Umbraco 8! 
The fix is in the class used on the svg.icon.picker.html! 
It needs to be updated from **"umb-editor"** to **"umb-property-editor"**  and the problem is fixed!

**Comment by michaelchart** [comment]
Any chance of doing a new Nuget release for this umbraco 8 compatible version?
