### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by bjarnef** [skttl/Umbraco.SvgIconPicker#2]
Any change you can create a NuGet package for this?

Maybe it could also be an option to decide whether to use svg spritesheet or just svg icons from a folder.
E.g. if path ends with `.svg` use sprite sheet otherwise look for `.svg` extensions in folder path.

**Comment by skttl** [comment]
I have been thinking about the same regarding spritesheets vs. single svgs. So I might do a v2 :)

Nuget is also a priority, seems like a lot of people want it, although I almost never use it in Umbraco Cloud solutions :)

**Comment by skttl** [comment]
Added a nuget :)
https://www.nuget.org/packages/skttl.Umbraco.SvgIconPicker/1.1.0

**Comment by bjarnef** [comment]
@skttl great! :)

Just curious which .NET Framework version the NuGet package is built for?

By default it seems packages.config on Umbraco Cloud is set to `targetFramework="net45"`, but this package targets a newer framework version.

![image](https://user-images.githubusercontent.com/2919859/33260565-8012942a-d360-11e7-904a-9dc392c5af83.png)

I don't have this issue with other NuGet packages like Nested Content, LeBlender, etc.

I can probably increase in `targetFramework` version, but I don't think there is any issue to change target version to .NET 4.5 since the package doesn't contain any server side code anyway :)

**Comment by skttl** [comment]
Yes, thats weird. I added a dependency on UmbracoCms.Core 7.4.0 and up.
Seems to work now.

https://www.nuget.org/packages/skttl.Umbraco.SvgIconPicker/1.1.1


man. 27. nov. 2017 kl. 10.55 skrev Bjarne Fyrstenborg <
notifications@github.com>:

**Comment by bjarnef** [comment]
Thanks, it works now.
![image](https://user-images.githubusercontent.com/2919859/33263284-85d9e0c6-d369-11e7-8aec-987ef03a468b.png)

But for some reason it doesn't update the files in `App_Plugins/SvgIconPicker`.
I tried to delete the existing files and when install the NuGet package it doesn't add these files.

The NuGet package does contain the files though.
![image](https://user-images.githubusercontent.com/2919859/33263402-021dc72e-d36a-11e7-969b-3f02c5e91ef0.png)

**Comment by bjarnef** [comment]
This is how it looks for my own package.

![image](https://user-images.githubusercontent.com/2919859/33264096-7d266cf8-d36c-11e7-9b81-e2cab8ba9f3a.png)

Is it missing reference to the files like this?
https://github.com/bjarnef/Switcher/blob/master/config/package.nuspec#L32-L34

The `package.nuspec` doesn't list any files:
https://github.com/skttl/Umbraco.SvgIconPicker/blob/master/config/package.nuspec

https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package
`content`:

> Contents are copied to the project root. Think of the content folder as the root of the target application that ultimately consumes the package. To have the package add an image in the application's /images folder, place it in the package's content/images folder.

**Comment by tomvanenckevort** [comment]
@skttl @bjarnef I just ran into the same issue, and it's also mentioned here: https://our.umbraco.org/projects/backoffice-extensions/svg-icon-picker/support/89782-nuget-version-not-installing

When I generate the NuGet package from the source in the repo here it generates the right NuGet package (with the App_Plugins folder inside a content folder), but it's v0.1.0, so I'm not sure if the current repo code is fully up-to-date?
