### ISSUE TITLE
SVG icon preview is too small

### ISSUE THREAD

**Issue by bjarnef** [skttl/Umbraco.SvgIconPicker#3]
I have used your package for a project, but the svg icon preview seems to be too small.

![image](https://user-images.githubusercontent.com/2919859/31667364-8afee16c-b34f-11e7-90e3-f2591de8ce9f.png)

Maybe change to this instead and ensure icon is centered horizontally.

![image](https://user-images.githubusercontent.com/2919859/31667434-bc176ddc-b34f-11e7-89a7-13b82cfd0039.png)

![image](https://user-images.githubusercontent.com/2919859/31667451-ca782cae-b34f-11e7-981c-f3b8e017707b.png)

**Comment by skttl** [comment]
Thanks, I'll look into that :)
