### ISSUE TITLE
Update preview box for Umbraco 7.6.10 and 7.7.3

### ISSUE THREAD

**Issue by bjarnef** [skttl/Umbraco.SvgIconPicker#4]
After upgrade from 7.6.9 to 7.6.10 the preview box is no longer a square because of this change:
https://github.com/umbraco/Umbraco-CMS/commit/dc937ec9425840e516ae0d4ee194e8f3916406c9#diff-5dfb1d66507966c2d20bbc69455d7045

and is an issue in 7.7.3 as aswell.

![image](https://user-images.githubusercontent.com/2919859/31679359-235a9dc2-b371-11e7-80f6-8ea20208cb78.png)

but if you add the same changes in your code, I guess it would fix it.

**Comment by bjarnef** [comment]
@skttl any change you have some time to take a look at some of the issue reported and maybe a new release of your package? :)

**Comment by skttl** [comment]
Would love to, but time is a bit limited at the moment.

tor. 16. nov. 2017 kl. 11.15 skrev Bjarne Fyrstenborg <
notifications@github.com>:

**Comment by bjarnef** [comment]
@skttl I have submitted a PR which fix these issues.

**Comment by skttl** [comment]
Great! I'll do a release in the coming days :)

tor. 23. nov. 2017 kl. 14.10 skrev Bjarne Fyrstenborg <
notifications@github.com>:
